#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        # Set the default settings of the service package to those expected by
        # OpenMediaVault.
        if [ -z "${2}" ]; then
            deb-systemd-helper disable mumble-server.service >/dev/null || true
            deb-systemd-invoke stop mumble-server.service >/dev/null || true
        fi

        SERVICE_XPATH_NAME="mumble"
        SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

        if ! omv_config_exists "${SERVICE_XPATH}"; then
            omv_config_add_node "/config/services" "${SERVICE_XPATH_NAME}"

            omv_config_add_key "${SERVICE_XPATH}" "enable" "0"
            omv_config_add_key "${SERVICE_XPATH}" "server_password" ""
            omv_config_add_key "${SERVICE_XPATH}" "bandwidth" "72000"
            omv_config_add_key "${SERVICE_XPATH}" "users" "100"
            omv_config_add_key "${SERVICE_XPATH}" "force_opus" "0"
        fi

        # Activate package triggers. These triggers are only set during the
        # package installation.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
